---
# roles/glusterfs/tasks/configure.yml
#
- name: glusterd service
  ansible.builtin.service:
    enabled: true
    name: glusterd.service
    state: started

- name: peers
  gluster.gluster.gluster_peer:
    nodes: "{{ cluster }}"
    state: present
  run_once: true

