---
# https://docs.gluster.org/en/latest/Administrator-Guide/SSL/
- name: glusterfs.pem
  #ansible.builtin.template:
  ansible.builtin.copy:
    content: "{{ glusterfs_pem }}"
    dest: "{{ glusterfs_pem_path }}"
    group: root
    #lstrip_blocks: yes
    mode: 0644
    owner: root
    #src: glusterfs.pem.j2
  notify:
    - restart glusterd

- name: glusterfs.key
  ansible.builtin.copy:
    content: "{{ glusterfs_key }}"
    dest: "{{ glusterfs_key_path }}"
    group: root
    mode: 0600
    owner: root
  notify:
    - restart glusterd

- name: glusterfs.ca
  ansible.builtin.copy:
    content: "{{ glusterfs_ca }}"
    dest: "{{ glusterfs_ca_path }}"
    group: root
    mode: 0644
    owner: root
  notify:
    - restart glusterd
