---
- name: partition disks
  community.general.parted:
    align: optimal
    device: "/dev/{{ item.dev }}"
    label: gpt
    name: "zpool"
    number: 1
    part_end: "100%"
    part_start: "0%"
    state: present
  with_items:
    - "{{ glusterfs_zpools }}"
